package sony.service;

import java.util.HashMap;
import java.util.Map;

import org.springframework.stereotype.Service;

import sony.model.Synopsis;

@Service
public class MovieServiceImpl implements MovieService {
	private Map<String, Synopsis> synopsisMap;
	
	// Initialize Mock Data
	public MovieServiceImpl() {
		synopsisMap = new HashMap<String, Synopsis>();
		synopsisMap.put("1", new Synopsis("Teenage Mutant Ninja Turtles", "The city needs heroes. Darkness has settled over New York City as Shredder and his evil Foot Clan have an iron grip on everything from the police to the politicians. The future is grim until four unlikely outcast brothers rise from the sewers and discover their destiny as Teenage Mutant Ninja Turtles. The Turtles must work with fearless reporter April O'Neil (Megan Fox) and her wise-cracking cameraman Vern Fenwick (Will Arnett) to save the city and unravel Shredder's diabolical plan. Based on the Teenage Mutant Ninja Turtles Characters Created by PETER LAIRD and KEVIN EASTMAN with a Screenplay by JOSH APPELBAUM & ANDRÉ NEMEC and EVAN DAUGHERTY, Teenage Mutant Ninja Turtles is produced by MICHAEL BAY (director and executive producer of the blockbuster Transformers franchise), Andrew Form, Brad Fuller, Galen Walker, Scott Mednick and Ian Bryce, and directed by JONATHAN LIEBESMAN (Wrath of the Titans).(c) Paramount"));
		synopsisMap.put("2", new Synopsis("Guardians of the Galaxy ", "From Marvel, the studio that brought you the global blockbuster franchises of Iron Man, Thor, Captain America and The Avengers, comes a new team-the Guardians of the Galaxy. An action-packed, epic space adventure, Marvel's \"Guardians of the Galaxy\" expands the Marvel Cinematic Universe into the cosmos, where brash adventurer Peter Quill finds himself the object of an unrelenting bounty hunt after stealing a mysterious orb coveted by Ronan, a powerful villain with ambitions that threaten the entire universe. To evade the ever-persistent Ronan, Quill is forced into an uneasy truce with a quartet of disparate misfits-Rocket, a gun-toting raccoon, Groot, a tree-like humanoid, the deadly and enigmatic Gamora and the revenge-driven Drax the Destroyer. But when Quill discovers the true power of the orb and the menace it poses to the cosmos, he must do his best to rally his ragtag rivals for a last, desperate stand-with the galaxy's fate in the balance. (C) Walt Disney"));
		synopsisMap.put("3", new Synopsis("Into The Storm", "In the span of a single day, the town of Silverton is ravaged by an unprecedented onslaught of tornadoes. The entire town is at the mercy of the erratic and deadly cyclones, even as storm trackers predict the worst is yet to come. Most people seek shelter, while others run towards the vortex, testing how far a storm chaser will go for that once-in-a-lifetime shot. Told through the eyes and lenses of professional storm chasers, thrill-seeking amateurs, and courageous townspeople, \"Into the Storm\" throws you directly into the eye of the storm to experience Mother Nature at her most extreme. (C) Warner Bros"));
		synopsisMap.put("4", new Synopsis("The Hundred-Foot Journey", "In \"The Hundred-Foot Journey,\" Hassan Kadam (Manish Dayal) is a culinary ingénue with the gastronomic equivalent of perfect pitch. Displaced from their native India, the Kadam family, led by Papa (Om Puri), settles in the quaint village of Saint-Antonin-Noble-Val in the south of France. Filled with charm, it is both picturesque and elegant - the ideal place to settle down and open an Indian restaurant, the Maison Mumbai. That is, until the chilly chef proprietress of Le Saule Pleureur, a Michelin starred, classical French restaurant run by Madame Mallory (Academy Award (R)-winner Helen Mirren), gets wind of it. Her icy protests against the new Indian restaurant a hundred feet from her own, escalate to all out war between the two establishments - until Hassan's passion for French haute cuisine and for Mme. Mallory's enchanting sous chef, Marguerite (Charlotte Le Bon), combine with his mysteriously delicious talent to weave magic between their two cultures and imbue Saint-Antonin with the flavors of life that even Mme. Mallory cannot ignore. At first Mme. Mallory's culinary rival, she eventually recognizes Hassan's gift as a chef and takes him under her wing. (c) Disney"));
		synopsisMap.put("5", new Synopsis("Lucy", "From La Femme Nikita and The Professional to The Fifth Element, writer/director Luc Besson has created some of the toughest, most memorable female action heroes in cinematic history. Now, Besson directs Scarlett Johansson in Lucy, an action-thriller that tracks a woman accidentally caught in a dark deal who turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic. (C) Universal"));
		synopsisMap.put("6", new Synopsis("Step Up: All In", "In the next exciting chapter of the international phenomenon STEP UP, all-stars from previous installments come together in glittering Las Vegas, battling for a victory that could define their dreams and their careers. (c) Lionsgate"));
		synopsisMap.put("7", new Synopsis("Hercules", "Paramount Pictures and Metro-Goldwyn-Mayer Pictures' film HERCULES, starring Dwayne Johnson, bows on July 25th. Based on Radical Comics' Hercules by Steve Moore, this ensemble-action film is a revisionist take on the classic myth, HERCULES. The epic action film also stars Golden Globe Winner Ian McShane, Rufus Sewell, Joseph Fiennes, Peter Mullan and Academy Award (R)-nominee John Hurt. (C) Paramount"));
		synopsisMap.put("8", new Synopsis("Get On Up", "In his follow-up to the four-time Academy Award (R)-nominated blockbuster The Help, Tate Taylor directs 42's Chadwick Boseman as James Brown in Get on Up. Based on the incredible life story of the Godfather of Soul, the film will give a fearless look inside the music, moves and moods of Brown, taking audiences on the journey from his impoverished childhood to his evolution into one of the most influential figures of the 20th century. Boseman is joined in the drama by Viola Davis, Octavia Spencer, Nelsan Ellis, Lennie James, Tika Sumpter, Jill Scott and Dan Aykroyd."));
		synopsisMap.put("9", new Synopsis("Dawn Of The Planet Of The Apes", "A growing nation of genetically evolved apes led by Caesar is threatened by a band of human survivors of the devastating virus unleashed a decade earlier. They reach a fragile peace, but it proves short-lived, as both sides are brought to the brink of a war that will determine who will emerge as Earth's dominant species. (c) Fox"));
		synopsisMap.put("10", new Synopsis("Planes: Fire And Rescue	4", "Adventure flies higher than ever before in this sequel to Disney's Planes. ~ Jason Buchanan, Rovi"));
	}

	public Synopsis getSynopsis(String movieId) {
		return synopsisMap.get(movieId);
	}
}
